name: Deploy to Github pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploying to Github pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set-up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
        working-directory: ./site
      - run: npm run build
        working-directory: ./site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site/dist
